repos:
-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'davenv/bin/pip freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [pre-commit]
